<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CreateBookingBody implements JsonSerializable
{
    /**
     * Desired date of booking.  Several formats are supported: "2014-10-31", "October 31, 2014"
     * @required
     * @var string $date public property
     */
    public $date;

    /**
     * ID of Service being booked
     * @required
     * @maps service_id
     * @var integer $serviceId public property
     */
    public $serviceId;

    /**
     * Desired time of booking.  Several formats are supported: '9am', '09:00', '9:00', '0900'
     * @required
     * @var string $time public property
     */
    public $time;

    /**
     * Required only when :recurs_by is 'monthly' or 'yearly' to differentiate between exact date or 'day in month/year'.  See Recurring Booking examples.
     * @maps date_recurs_by
     * @var string|null $dateRecursBy public property
     */
    public $dateRecursBy;

    /**
     * List of comma-separated days of the week this Booking falls on.  Useful for recurring Bookings.  If provided, at least one must be specified.
     * @var string|null $days public property
     */
    public $days;

    /**
     * Length of time, in minutes, for the desired booking - if Service allows requesting a variable amount of time
     * @var integer|null $duration public property
     */
    public $duration;

    /**
     * Optional end date if a recurring booking - i.e, :recurs_by other than :once.  If recurring, leave blank for infinite booking.  Several formats are supported: '2014-10-31', 'October 31, 2014'.
     * @maps end_date
     * @var string|null $endDate public property
     */
    public $endDate;

    /**
     * Optional frequency of recurrence as specified by :recurs_by.  E.g, :single, :every, :every_other, etc. If not provided, assumed to be :once
     * @var string|null $frequency public property
     */
    public $frequency;

    /**
     * Optional occurrence of frequency. E.g, :first, :2nd, :last, :2nd_to_last, etc.  If not provided, assumed to be :every
     * @var string|null $occurrence public property
     */
    public $occurrence;

    /**
     * One of the possible recurrence values.  If not provided, assumed to be :once to indicate a single Booking.
     * @maps recurs_by
     * @var string|null $recursBy public property
     */
    public $recursBy;

    /**
     * ID of a Resource to be booked.  If not provided, the first available Resource will be booked.
     * @maps resource_id
     * @var integer|null $resourceId public property
     */
    public $resourceId;

    /**
     * Create a booking for this User Id.  You must be authorized to manage this User Id.
     * @maps user_id
     * @var integer|null $userId public property
     */
    public $userId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $date         Initialization value for $this->date
     * @param integer $serviceId    Initialization value for $this->serviceId
     * @param string  $time         Initialization value for $this->time
     * @param string  $dateRecursBy Initialization value for $this->dateRecursBy
     * @param string  $days         Initialization value for $this->days
     * @param integer $duration     Initialization value for $this->duration
     * @param string  $endDate      Initialization value for $this->endDate
     * @param string  $frequency    Initialization value for $this->frequency
     * @param string  $occurrence   Initialization value for $this->occurrence
     * @param string  $recursBy     Initialization value for $this->recursBy
     * @param integer $resourceId   Initialization value for $this->resourceId
     * @param integer $userId       Initialization value for $this->userId
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->date         = func_get_arg(0);
            $this->serviceId    = func_get_arg(1);
            $this->time         = func_get_arg(2);
            $this->dateRecursBy = func_get_arg(3);
            $this->days         = func_get_arg(4);
            $this->duration     = func_get_arg(5);
            $this->endDate      = func_get_arg(6);
            $this->frequency    = func_get_arg(7);
            $this->occurrence   = func_get_arg(8);
            $this->recursBy     = func_get_arg(9);
            $this->resourceId   = func_get_arg(10);
            $this->userId       = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['date']           = $this->date;
        $json['service_id']     = $this->serviceId;
        $json['time']           = $this->time;
        $json['date_recurs_by'] = $this->dateRecursBy;
        $json['days']           = $this->days;
        $json['duration']       = $this->duration;
        $json['end_date']       = $this->endDate;
        $json['frequency']      = $this->frequency;
        $json['occurrence']     = $this->occurrence;
        $json['recurs_by']      = $this->recursBy;
        $json['resource_id']    = $this->resourceId;
        $json['user_id']        = $this->userId;

        return $json;
    }
}
