<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class EntitiesAddressEntity implements JsonSerializable
{
    /**
     * city of Address
     * @var string|null $city public property
     */
    public $city;

    /**
     * country of Address
     * @var string|null $country public property
     */
    public $country;

    /**
     * country code of Address
     * @maps country_code
     * @var string|null $countryCode public property
     */
    public $countryCode;

    /**
     * latitude of Address
     * @var string|null $latitude public property
     */
    public $latitude;

    /**
     * line 1 of Address
     * @var string|null $line1 public property
     */
    public $line1;

    /**
     * line 2 of Address
     * @var string|null $line2 public property
     */
    public $line2;

    /**
     * longitude of Address
     * @var string|null $longitude public property
     */
    public $longitude;

    /**
     * postal code of Address
     * @maps postal_code
     * @var string|null $postalCode public property
     */
    public $postalCode;

    /**
     * province of Address
     * @var string|null $province public property
     */
    public $province;

    /**
     * state of Address
     * @var string|null $state public property
     */
    public $state;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $city        Initialization value for $this->city
     * @param string $country     Initialization value for $this->country
     * @param string $countryCode Initialization value for $this->countryCode
     * @param string $latitude    Initialization value for $this->latitude
     * @param string $line1       Initialization value for $this->line1
     * @param string $line2       Initialization value for $this->line2
     * @param string $longitude   Initialization value for $this->longitude
     * @param string $postalCode  Initialization value for $this->postalCode
     * @param string $province    Initialization value for $this->province
     * @param string $state       Initialization value for $this->state
     */
    public function __construct()
    {
        if (10 == func_num_args()) {
            $this->city        = func_get_arg(0);
            $this->country     = func_get_arg(1);
            $this->countryCode = func_get_arg(2);
            $this->latitude    = func_get_arg(3);
            $this->line1       = func_get_arg(4);
            $this->line2       = func_get_arg(5);
            $this->longitude   = func_get_arg(6);
            $this->postalCode  = func_get_arg(7);
            $this->province    = func_get_arg(8);
            $this->state       = func_get_arg(9);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['city']         = $this->city;
        $json['country']      = $this->country;
        $json['country_code'] = $this->countryCode;
        $json['latitude']     = $this->latitude;
        $json['line1']        = $this->line1;
        $json['line2']        = $this->line2;
        $json['longitude']    = $this->longitude;
        $json['postal_code']  = $this->postalCode;
        $json['province']     = $this->province;
        $json['state']        = $this->state;

        return $json;
    }
}
