<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class EntitiesResourceResponse implements JsonSerializable
{
    /**
     * capacity of Resource, if applicable
     * @var integer|null $capacity public property
     */
    public $capacity;

    /**
     * description of Resource
     * @var string|null $description public property
     */
    public $description;

    /**
     * gender of Resource, if applicable
     * @var string|null $gender public property
     */
    public $gender;

    /**
     * id of Resource
     * @var integer|null $id public property
     */
    public $id;

    /**
     * name of Resource
     * @var string|null $name public property
     */
    public $name;

    /**
     * id of User owning Resource
     * @maps owner_id
     * @var integer|null $ownerId public property
     */
    public $ownerId;

    /**
     * if Calendar is primary, if applicable
     * @maps primary_cal
     * @var bool|null $primaryCal public property
     */
    public $primaryCal;

    /**
     * type of Resource
     * @maps resource_type
     * @var string|null $resourceType public property
     */
    public $resourceType;

    /**
     * type Id of Thing Resource, if applicable
     * @maps thing_type_id
     * @var integer|null $thingTypeId public property
     */
    public $thingTypeId;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $capacity     Initialization value for $this->capacity
     * @param string  $description  Initialization value for $this->description
     * @param string  $gender       Initialization value for $this->gender
     * @param integer $id           Initialization value for $this->id
     * @param string  $name         Initialization value for $this->name
     * @param integer $ownerId      Initialization value for $this->ownerId
     * @param bool    $primaryCal   Initialization value for $this->primaryCal
     * @param string  $resourceType Initialization value for $this->resourceType
     * @param integer $thingTypeId  Initialization value for $this->thingTypeId
     */
    public function __construct()
    {
        if (9 == func_num_args()) {
            $this->capacity     = func_get_arg(0);
            $this->description  = func_get_arg(1);
            $this->gender       = func_get_arg(2);
            $this->id           = func_get_arg(3);
            $this->name         = func_get_arg(4);
            $this->ownerId      = func_get_arg(5);
            $this->primaryCal   = func_get_arg(6);
            $this->resourceType = func_get_arg(7);
            $this->thingTypeId  = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['capacity']      = $this->capacity;
        $json['description']   = $this->description;
        $json['gender']        = $this->gender;
        $json['id']            = $this->id;
        $json['name']          = $this->name;
        $json['owner_id']      = $this->ownerId;
        $json['primary_cal']   = $this->primaryCal;
        $json['resource_type'] = $this->resourceType;
        $json['thing_type_id'] = $this->thingTypeId;

        return $json;
    }
}
