<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class EntitiesTimeWindowResponse implements JsonSerializable
{
    /**
     * date_recurs_by
     * @maps date_recurs_by
     * @var string|null $dateRecursBy public property
     */
    public $dateRecursBy;

    /**
     * array of days of week TimeWindow falls on
     * @var array|null $days public property
     */
    public $days;

    /**
     * end date
     * @maps end_date
     * @var string|null $endDate public property
     */
    public $endDate;

    /**
     * end time
     * @maps end_time
     * @var string|null $endTime public property
     */
    public $endTime;

    /**
     * frequency
     * @var string|null $frequency public property
     */
    public $frequency;

    /**
     * id of TimeWindow
     * @var integer|null $id public property
     */
    public $id;

    /**
     * occurrence
     * @var string|null $occurrence public property
     */
    public $occurrence;

    /**
     * recurs by
     * @maps recurs_by
     * @var string|null $recursBy public property
     */
    public $recursBy;

    /**
     * start date
     * @maps start_date
     * @var string|null $startDate public property
     */
    public $startDate;

    /**
     * start time
     * @maps start_time
     * @var string|null $startTime public property
     */
    public $startTime;

    /**
     * total minutes spanned
     * @maps total_minutes
     * @var integer|null $totalMinutes public property
     */
    public $totalMinutes;

    /**
     * true is available, false is unavailable
     * @var bool|null $unavailable public property
     */
    public $unavailable;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $dateRecursBy Initialization value for $this->dateRecursBy
     * @param array   $days         Initialization value for $this->days
     * @param string  $endDate      Initialization value for $this->endDate
     * @param string  $endTime      Initialization value for $this->endTime
     * @param string  $frequency    Initialization value for $this->frequency
     * @param integer $id           Initialization value for $this->id
     * @param string  $occurrence   Initialization value for $this->occurrence
     * @param string  $recursBy     Initialization value for $this->recursBy
     * @param string  $startDate    Initialization value for $this->startDate
     * @param string  $startTime    Initialization value for $this->startTime
     * @param integer $totalMinutes Initialization value for $this->totalMinutes
     * @param bool    $unavailable  Initialization value for $this->unavailable
     */
    public function __construct()
    {
        if (12 == func_num_args()) {
            $this->dateRecursBy = func_get_arg(0);
            $this->days         = func_get_arg(1);
            $this->endDate      = func_get_arg(2);
            $this->endTime      = func_get_arg(3);
            $this->frequency    = func_get_arg(4);
            $this->id           = func_get_arg(5);
            $this->occurrence   = func_get_arg(6);
            $this->recursBy     = func_get_arg(7);
            $this->startDate    = func_get_arg(8);
            $this->startTime    = func_get_arg(9);
            $this->totalMinutes = func_get_arg(10);
            $this->unavailable  = func_get_arg(11);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['date_recurs_by'] = $this->dateRecursBy;
        $json['days']           = $this->days;
        $json['end_date']       = $this->endDate;
        $json['end_time']       = $this->endTime;
        $json['frequency']      = $this->frequency;
        $json['id']             = $this->id;
        $json['occurrence']     = $this->occurrence;
        $json['recurs_by']      = $this->recursBy;
        $json['start_date']     = $this->startDate;
        $json['start_time']     = $this->startTime;
        $json['total_minutes']  = $this->totalMinutes;
        $json['unavailable']    = $this->unavailable;

        return $json;
    }
}
