<?php
/*
 * GonebusyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class FrequencyEnum
{
    /**
     * TODO: Write general description for this element
     */
    const SINGLE = "single";

    /**
     * TODO: Write general description for this element
     */
    const EVERY = "every";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_OTHER = "every_other";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_3RD = "every_3rd";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_4TH = "every_4th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_5TH = "every_5th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_6TH = "every_6th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_7TH = "every_7th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_8TH = "every_8th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_9TH = "every_9th";

    /**
     * TODO: Write general description for this element
     */
    const EVERY_10TH = "every_10th";
}
