<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class GenderEnum
{
    /**
     * TODO: Write general description for this element
     */
    const F = "F";

    /**
     * TODO: Write general description for this element
     */
    const M = "M";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_TG = "T/G";
}
