<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetCategoryByIdResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var EntitiesCategoryResponse|null $category public property
     */
    public $category;

    /**
     * Constructor to set initial or default values of member properties
     * @param EntitiesCategoryResponse $category Initialization value for $this->category
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->category = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['category'] = $this->category;

        return $json;
    }
}
