<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetPricingModelsResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps pricing_models
     * @var EntitiesPricingModelResponse[]|null $pricingModels public property
     */
    public $pricingModels;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $pricingModels Initialization value for $this->pricingModels
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->pricingModels = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['pricing_models'] = $this->pricingModels;

        return $json;
    }
}
