<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GetSchedulesResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var EntitiesScheduleResponse[]|null $schedules public property
     */
    public $schedules;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $schedules Initialization value for $this->schedules
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->schedules = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['schedules'] = $this->schedules;

        return $json;
    }
}
