<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class OccurrenceEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ENUM_4TH_TO_LAST = "4th_to_last";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_3RD_TO_LAST = "3rd_to_last";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_2ND_TO_LAST = "2nd_to_last";

    /**
     * TODO: Write general description for this element
     */
    const LAST = "last";

    /**
     * TODO: Write general description for this element
     */
    const EVERY = "every";

    /**
     * TODO: Write general description for this element
     */
    const FIRST = "first";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_2ND = "2nd";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_3RD = "3rd";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_4TH = "4th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_5TH = "5th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_6TH = "6th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_7TH = "7th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_8TH = "8th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_9TH = "9th";

    /**
     * TODO: Write general description for this element
     */
    const ENUM_10TH = "10th";
}
