<?php
/*
 * GonebusyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class RecursByEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ONCE = "once";

    /**
     * TODO: Write general description for this element
     */
    const DAILY = "daily";

    /**
     * TODO: Write general description for this element
     */
    const WEEKEND = "weekend";

    /**
     * TODO: Write general description for this element
     */
    const MON_WED_FRI = "mon_wed_fri";

    /**
     * TODO: Write general description for this element
     */
    const TUE_THU = "tue_thu";

    /**
     * TODO: Write general description for this element
     */
    const WEEKDAY = "weekday";

    /**
     * TODO: Write general description for this element
     */
    const WEEKLY = "weekly";

    /**
     * TODO: Write general description for this element
     */
    const MONTHLY = "monthly";

    /**
     * TODO: Write general description for this element
     */
    const YEARLY = "yearly";
}
