<?php
/*
 * GonebusyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib;

class CustomAuthUtility
{
    /**
    * Appends the necessary Custom Authentication credentials for making this authorized call
    * @param HttpRequest $request The out going request to access the resource
    */
    public static function appendCustomAuthParams($request)
    {
        // TODO: Add your custom authentication here
        // The following properties are available to use
        //     Configuration::$authorization
        // 
        // ie. Add a header through:
        //     $request.headers(array("key" => "value"));
    }
}