<?php
/*
 * Gonebusy
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * TODO: Write general description for this element
     */
    const PRODUCTION = "production";

    /**
     * https://sandbox.gonebusy.com/api/v1
     */
    const SANDBOX = "sandbox";
}
