<?php
/*
 * GonebusyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const DEFAULT_ = "default";
}
